#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Pallavi Anderson

Additional software to install

Browsers:
    Firefox
    Google Chrome

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
		TextMate
    VirtualBox
    XAMPP
		XCode
    RVM: $ \curl -L https://get.rvm.io | bash -s stable --rails --autolibs=enable
    Eclipse
      JavaSE
    Octave: http://wiki.octave.org/Octave_for_MacOS_X#Binary_installer_for_OSX_10.9.1 
  
Other:
    Alfred
    Divvy
    Dropbox
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
		Solarized themes
    uTorrent
    VLC
EOT

}
