#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Pallavi Anderson

Additional software to install

Browsers:
    Firefox
    Google Chrome

Development:
    Filezilla
    iTerm 2
    ImageAlpha
    ImageOptim
		TextMate
    VirtualBox
    XAMPP
		XCode

Other:
    Alfred
    Divvy
    Dropbox
    Flux
    KeePassX
    LimeChat
    Network Connect
    Skype
		Solarized themes
    uTorrent
    VLC
    RVM: $ \curl -L https://get.rvm.io | bash -s stable --rails --autolibs=enable
EOT

}
